require "file_utils"

module Jasper
  class Generator
    property config : Config
    property pipeline : Pipeline

    def initialize(@config : Config = Config.new, @pipeline : Pipeline = Jasper.pipeline)
    end

    def self.run(config : Config = Config.new) : Bool
      new(config).run
    end

    def run : Bool
      src = Path.new(@config.source_dir)
      out_dir = Path.new(@config.output_dir)
      master_file = Path.new(@config.master_file)

      documents = [] of DocDocument

      # 1. Discover YAML files if source directory exists
      if Dir.exists?(src)
        clean_src = src.to_s.tr("\\", "/")
        pattern = "#{clean_src}/**/*.yml"
        yaml_files = Dir.glob(pattern).sort
        yaml_files.each do |yfile|
          content = File.read(yfile)
          begin
            doc = DocDocument.from_yaml(content)
            documents << doc
          rescue ex
            # Skip or log malformed file
          end
        end
      end

      # 2. Add programmatic documents from DSL
      Jasper.programmatic_documents.each do |pdoc|
        documents << pdoc unless documents.any? { |d| d.id == pdoc.id }
      end

      return false if documents.empty?

      FileUtils.mkdir_p(out_dir)
      FileUtils.mkdir_p(master_file.dirname) unless Dir.exists?(master_file.dirname)

      # Pipeline before_build hook
      ctx = Pipeline::Context.new(@config)
      ctx.documents = documents
      @pipeline.trigger_before_build(ctx)

      # Group by parent module
      first_doc = documents.first?
      default_root = if first_doc && (rm = first_doc.root_module)
                       rm
                     else
                       @config.namespace
                     end

      grouped = Hash(String, Array(DocDocument)).new { |h, k| h[k] = [] of DocDocument }
      documents.each do |doc|
        doc.root_module ||= default_root
        @pipeline.trigger_on_document(doc, ctx)
        grouped[doc.resolved_parent_module(default_root)] << doc
      end

      generated_rel_paths = [] of String

      # 3. Generate each submodule file
      grouped.each do |parent_mod, docs_list|
        parent_slug = parent_mod.split("::").last.downcase
        topic_dir = out_dir.join(parent_slug)
        FileUtils.mkdir_p(topic_dir)

        docs_list.each do |doc|
          sub_slug = doc.id.downcase
          out_file = topic_dir.join("#{sub_slug}.cr")
          cr_code = render_submodule_code(doc, default_root)
          File.write(out_file, cr_code)

          prefix = out_dir.relative_to(master_file.dirname).to_s.tr("\\", "/")
          rel_path = "#{prefix}/#{parent_slug}/#{sub_slug}"
          generated_rel_paths << rel_path
        end
      end

      # 4. Generate master file
      generate_master_file(master_file, grouped, generated_rel_paths, default_root)

      # 5. Export search index if configured
      if idx_path = @config.features.search_index_file
        FileUtils.mkdir_p(Path.new(idx_path).dirname) unless Dir.exists?(Path.new(idx_path).dirname)
        Indexer.export_json(documents, idx_path, default_root)
      end

      # Pipeline after_build hook
      @pipeline.trigger_after_build(ctx)

      true
    end

    private def render_submodule_code(doc : DocDocument, default_root : String) : String
      parent_parts = doc.resolved_parent_module(default_root).split("::")
      top_topic = parent_parts.last

      root_parts = if rm = doc.root_module
                     rm.split("::")
                   elsif parent_parts.size > 1
                     parent_parts[0...-1]
                   else
                     default_root.split("::")
                   end

      String.build do |io|
        io.puts "# =============================================================================="
        io.puts "# Auto-generated by Jasper (https://github.com/sol-vin/jasper)"
        io.puts "# DO NOT EDIT MANUALLY - Edit source documentation in #{@config.source_dir}/ instead"
        io.puts "# =============================================================================="
        io.puts
        io.puts "{% unless flag?(:release) %}" if @config.features.release_guard
        root_parts.each_with_index do |part, idx|
          io.puts "#{"  " * idx}module #{part}"
        end
        indent = root_parts.size
        io.puts "#{"  " * indent}module #{top_topic}"

        pad = "  " * (indent + 1)

        # Module-level documentation
        io.puts "#{pad}# # #{doc.title}"
        io.puts "#{pad}#"
        if overview = doc.overview
          overview_filtered = @pipeline.apply_markdown_filters(overview)
          overview_filtered.lines.each do |l|
            io.puts "#{pad}# #{l}".rstrip
          end
          io.puts "#{pad}#"
        end

        # Summary Table of Sections
        if @config.features.summary_table && !doc.sections.empty?
          io.puts "#{pad}# ### Executive Summary & Key Topics"
          io.puts "#{pad}#"
          io.puts "#{pad}# <table>"
          io.puts "#{pad}#   <thead>"
          io.puts "#{pad}#     <tr>"
          io.puts "#{pad}#       <th>Topic</th>"
          io.puts "#{pad}#       <th>Method / Anchor</th>"
          io.puts "#{pad}#       <th>Description</th>"
          io.puts "#{pad}#     </tr>"
          io.puts "#{pad}#   </thead>"
          io.puts "#{pad}#   <tbody>"
          doc.sections.each_with_index do |sec, sidx|
            method_name = resolve_method_name(sec.id, sidx)
            io.puts "#{pad}#     <tr>"
            io.puts "#{pad}#       <td><strong>#{sec.title}</strong></td>"
            io.puts "#{pad}#       <td><code>.#{method_name}</code></td>"
            clean_summary = sec.summary.gsub("<", "&lt;").gsub(">", "&gt;")
            io.puts "#{pad}#       <td>#{clean_summary}</td>"
            io.puts "#{pad}#     </tr>"
          end
          io.puts "#{pad}#   </tbody>"
          io.puts "#{pad}# </table>"
          io.puts "#{pad}#"
        end

        # Related Sources
        if sources = doc.related_sources
          io.puts "#{pad}# ### Related Guides & Source References"
          sources.each do |s|
            io.puts "#{pad}# - #{s}"
          end
          io.puts "#{pad}#"
        end

        io.puts "#{pad}module #{doc.id}"

        # Render each section as a method
        doc.sections.each_with_index do |sec, idx|
          io.puts if idx > 0
          render_section_method(io, sec, idx, indent_level: indent + 2)
        end

        io.puts "#{pad}end"
        io.puts "#{"  " * indent}end"
        (root_parts.size - 1).downto(0) do |i|
          io.puts "#{"  " * i}end"
        end
        io.puts "{% end %}" if @config.features.release_guard
      end
    end

    private def resolve_method_name(raw_id : String, index : Int32) : String
      slug = raw_id.downcase.gsub(/[^a-z0-9_]/, "_")
      if @config.features.naming_style == "prefixed"
        if slug.starts_with?("topic_")
          slug
        else
          sprintf(@config.features.prefix_format, index + 1) + slug
        end
      else
        slug
      end
    end

    private def render_section_method(io : IO, sec : DocSection, index : Int32, indent_level : Int32 = 4)
      m_pad = "  " * indent_level

      # Summary line
      io.puts "#{m_pad}#{MarkdownConverter.format_summary_line(sec.title, sec.summary, @config.features.protect_summary)}"
      io.puts "#{m_pad}#"

      # Main content
      if content = sec.content
        filtered = @pipeline.apply_markdown_filters(content)
        doc_content = MarkdownConverter.to_doc_comments(
          filtered,
          indent_level: indent_level,
          convert_tables: @config.features.table_auto_html
        )
        io.puts doc_content
        io.puts "#{m_pad}#"
      end

      # Options table
      if options = sec.options
        io.puts "#{m_pad}# #### Command Options & Flags"
        io.puts "#{m_pad}#"
        io.puts "#{m_pad}# <table>"
        io.puts "#{pad_or_indent(m_pad, 1)}<thead>"
        io.puts "#{pad_or_indent(m_pad, 2)}<tr>"
        io.puts "#{pad_or_indent(m_pad, 3)}<th>Flag / Option</th>"
        io.puts "#{pad_or_indent(m_pad, 3)}<th>Description</th>"
        io.puts "#{pad_or_indent(m_pad, 2)}</tr>"
        io.puts "#{pad_or_indent(m_pad, 1)}</thead>"
        io.puts "#{pad_or_indent(m_pad, 1)}<tbody>"
        options.each do |opt, desc|
          io.puts "#{pad_or_indent(m_pad, 2)}<tr>"
          io.puts "#{pad_or_indent(m_pad, 3)}<td><code>#{opt}</code></td>"
          io.puts "#{pad_or_indent(m_pad, 3)}<td>#{desc}</td>"
          io.puts "#{pad_or_indent(m_pad, 2)}</tr>"
        end
        io.puts "#{pad_or_indent(m_pad, 1)}</tbody>"
        io.puts "#{m_pad}# </table>"
        io.puts "#{m_pad}#"
      end

      # Code examples
      if examples = sec.examples
        io.puts "#{m_pad}# #### Working Examples"
        io.puts "#{m_pad}#"
        examples.each do |ex|
          ex.lines.each do |el|
            io.puts "#{m_pad}# #{el}".rstrip
          end
          io.puts "#{m_pad}#"
        end
      end

      # Common pitfalls
      if pitfalls = sec.pitfalls
        io.puts "#{m_pad}# #### Common Pitfalls & Safety Caveats"
        io.puts "#{m_pad}#"
        pitfalls.each do |pf|
          io.puts "#{m_pad}# - **Warning**: #{pf}"
        end
        io.puts "#{m_pad}#"
      end

      # FAQs
      if faqs = sec.faqs
        io.puts "#{m_pad}# #### Frequently Asked Questions (FAQ)"
        io.puts "#{m_pad}#"
        faqs.each do |faq|
          q = faq["q"]? || "Question"
          a = faq["a"]? || "Answer"
          io.puts "#{m_pad}# - **Q: #{q}**"
          io.puts "#{m_pad}#   A: #{a}"
          io.puts "#{m_pad}#"
        end
      end

      # Topics / information items
      topic_items = sec.topics || sec.items || sec.return_value
      if topic_items && !topic_items.empty?
        io.puts "#{m_pad}# #### Key Topics & Information"
        io.puts "#{m_pad}#"
        topic_items.each do |item|
          io.puts "#{m_pad}# - #{item}"
        end
        io.puts "#{m_pad}#"
      end

      # Custom plugin section handlers
      if custom_data = sec.custom_data
        custom_data.each do |custom_key, val|
          if handler = @pipeline.section_handlers[custom_key]?
            handler.call(io, val, m_pad)
          end
        end
      end

      method_name = resolve_method_name(sec.id, index)
      io.puts "#{m_pad}def self.#{method_name} : Nil; end"
    end

    private def pad_or_indent(base_pad : String, extra_levels : Int32) : String
      "#{base_pad}# #{"  " * extra_levels}"
    end

    private def generate_master_file(
      master_file : Path,
      grouped : Hash(String, Array(DocDocument)),
      generated_rel_paths : Array(String),
      default_root : String,
    ) : Nil
      root_parts = default_root.split("::")
      full_root_name = default_root

      content = String.build do |io|
        io.puts "# =============================================================================="
        io.puts "# #{full_root_name} Documentation System - Master Index & Navigation Hub"
        io.puts "# Auto-generated by Jasper (https://github.com/sol-vin/jasper)"
        io.puts "# =============================================================================="
        io.puts
        io.puts "{% unless flag?(:release) %}" if @config.features.release_guard

        root_parts[0...-1].each_with_index do |part, idx|
          io.puts "#{"  " * idx}module #{part}"
        end
        indent = root_parts.size - 1
        pad = "  " * indent

        io.puts "#{pad}# The `#{full_root_name}` module is the authoritative technical reference and documentation guide."
        io.puts "#{pad}#"

        if @config.features.master_index
          io.puts "#{pad}# ## Learning Tracks & Topic Index"
          io.puts "#{pad}#"
          io.puts "#{pad}# The documentation is paced into #{grouped.size} distinct tracks:"
          io.puts "#{pad}#"

          grouped.keys.sort.each_with_index do |parent_mod, idx|
            docs_list = grouped[parent_mod]
            top_topic = parent_mod.split("::").last
            track_num = idx + 1
            human_name = top_topic.sub(/^[A-Z]_/, "").gsub("_", " ").capitalize

            io.puts "#{pad}# ### #{track_num}. #{human_name} (`#{top_topic}`)"
            io.puts "#{pad}# <table>"
            io.puts "#{pad}#   <thead>"
            io.puts "#{pad}#     <tr>"
            io.puts "#{pad}#       <th>Submodule</th>"
            io.puts "#{pad}#       <th>Title</th>"
            io.puts "#{pad}#       <th>Description</th>"
            io.puts "#{pad}#     </tr>"
            io.puts "#{pad}#   </thead>"
            io.puts "#{pad}#   <tbody>"
            docs_list.each do |doc|
              io.puts "#{pad}#     <tr>"
              io.puts "#{pad}#       <td><code>#{doc.id}</code></td>"
              io.puts "#{pad}#       <td><strong>#{doc.title}</strong></td>"
              io.puts "#{pad}#       <td>#{doc.summary}</td>"
              io.puts "#{pad}#     </tr>"
            end
            io.puts "#{pad}#   </tbody>"
            io.puts "#{pad}# </table>"
            io.puts "#{pad}#"
          end
        end

        io.puts "#{pad}module #{root_parts.last}"

        # Quick start
        qs_title = if qs = @config.features.quick_start
                     qs.title
                   else
                     "#{root_parts.first} Quick Start"
                   end
        qs_commands = if qs = @config.features.quick_start
                        qs.commands
                      elsif full_root_name == "Lapis::Docs"
                        [
                          "lapis doctor     # Diagnose developer environment & dependencies",
                          "lapis new game   # Scaffold brand new Crystal Godot game",
                          "make all         # Compile bridge, test suites, examples, and sync",
                          "make test        # Execute specs, in-editor tool tests, and runtime suites",
                          "make editor      # Launch test project in Godot Editor",
                          "make docs        # Build offline HTML documentation site in docs/",
                        ]
                      else
                        [
                          "make docs        # Build offline HTML documentation site in docs/",
                          "make test        # Execute specifications and test suites",
                          "make all         # Build and verify all targets",
                        ]
                      end

        io.puts "#{pad}  # **Quick-Start Commands**: Essential commands for building, running, and testing."
        io.puts "#{pad}  #"
        io.puts "#{pad}  # #### #{qs_title}:"
        io.puts "#{pad}  # ```bash"
        qs_commands.each do |cmd|
          io.puts "#{pad}  # #{cmd}"
        end
        io.puts "#{pad}  # ```"
        io.puts "#{pad}  def self.topic_01_quick_start : Nil; end"
        io.puts

        # Reading paths
        if @config.features.master_index
          io.puts "#{pad}  # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced."
          io.puts "#{pad}  #"
          io.puts "#{pad}  # #### Structured Learning Tracks"
          io.puts "#{pad}  #"
          grouped.keys.sort.each_with_index do |parent_mod, idx|
            docs_list = grouped[parent_mod]
            top_topic = parent_mod.split("::").last
            track_num = idx + 1
            human_name = top_topic.sub(/^[A-Z]_/, "").gsub("_", " ").capitalize

            io.puts "#{pad}  # ##### #{track_num}. #{human_name} (`#{top_topic}`)"
            docs_list.each do |doc|
              clean_summary = doc.summary.gsub("<", "&lt;").gsub(">", "&gt;")
              io.puts "#{pad}  # - `#{top_topic}::#{doc.id}`: **#{doc.title}** &mdash; #{clean_summary}"
            end
            io.puts "#{pad}  #"
          end
          io.puts "#{pad}  def self.topic_02_reading_paths : Nil; end"
          io.puts

          # Table of contents
          io.puts "#{pad}  # **Master Table of Contents**: Complete hierarchical topic index."
          io.puts "#{pad}  #"
          io.puts "#{pad}  # #### Complete Documentation Index"
          io.puts "#{pad}  #"
          grouped.keys.sort.each do |parent_mod|
            docs_list = grouped[parent_mod]
            top_topic = parent_mod.split("::").last
            io.puts "#{pad}  # ##### `#{top_topic}`"
            docs_list.each do |doc|
              clean_summary = doc.summary.gsub("<", "&lt;").gsub(">", "&gt;")
              io.puts "#{pad}  # - `#{top_topic}::#{doc.id}`: **#{doc.title}** &mdash; #{clean_summary}"
            end
            io.puts "#{pad}  #"
          end
          io.puts "#{pad}  def self.topic_03_table_of_contents : Nil; end"
          io.puts

          io.puts "#{pad}  # :nodoc:"
          io.puts "#{pad}  def self.quick_start : Nil; topic_01_quick_start; end"
          io.puts "#{pad}  # :nodoc:"
          io.puts "#{pad}  def self.reading_paths : Nil; topic_02_reading_paths; end"
          io.puts "#{pad}  # :nodoc:"
          io.puts "#{pad}  def self.table_of_contents : Nil; topic_03_table_of_contents; end"
        end

        root_parts.size.times do |i|
          idx = root_parts.size - 1 - i
          io.puts "#{"  " * idx}end"
        end
        io.puts

        # Submodule requires
        generated_rel_paths.each do |rel|
          io.puts "require \"./#{rel}\""
        end

        # Aliases
        unless @config.features.aliases.empty?
          io.puts
          @config.features.aliases.each do |al|
            io.puts "alias #{al} = ::#{full_root_name}"
          end
        end

        if root_parts.first == "Lapis"
          io.puts
          io.puts "module Godot"
          io.puts "  alias Docs = ::Lapis::Docs"
          io.puts "end"
        end

        io.puts "{% end %}" if @config.features.release_guard
      end

      File.write(master_file, content)
    end
  end
end
